# Generated by Django 4.0.5 on 2022-07-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='admin',
            name='stages',
            field=models.CharField(choices=[('investigation', 'investigation'), ('rejected', 'rejected'), ('resolved', 'resolved')], default='investigation', max_length=20),
        ),
        migrations.AddField(
            model_name='intervention',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='redflag',
            name='location',
            field=models.TextField(blank=True),
        ),
    ]
