# Generated by Django 4.0.5 on 2022-07-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_status_admin_stages_intervention_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='stages',
        ),
        migrations.AddField(
            model_name='intervention',
            name='stages',
            field=models.CharField(choices=[('investigation', 'investigation'), ('rejected', 'rejected'), ('resolved', 'resolved')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='redflag',
            name='stages',
            field=models.CharField(choices=[('investigation', 'investigation'), ('rejected', 'rejected'), ('resolved', 'resolved')], default='', max_length=20),
        ),
    ]
