# Generated by Django 4.0.5 on 2022-07-04 19:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_admin_stages_intervention_stages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redflag',
            name='user',
        ),
        migrations.AlterField(
            model_name='intervention',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/ireporter2022/image/upload/v1656953718/crime5_r8mbnm.jpg', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redflag',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/ireporter2022/image/upload/v1656953718/crime5_r8mbnm.jpg', max_length=255, null=True),
        ),
    ]
