# Generated by Django 4.0.5 on 2022-07-04 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_redflag_user_alter_intervention_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redflag',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='app.client'),
        ),
    ]
