# Generated by Django 4.0.5 on 2022-07-05 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_redflag_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='stages',
            field=models.CharField(choices=[('investigation', 'investigation'), ('rejected', 'rejected'), ('resolved', 'resolved')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='app.client'),
        ),
    ]
