# Generated by Django 4.0.5 on 2022-07-05 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_intervention_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='app.client'),
        ),
        migrations.AlterField(
            model_name='redflag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='app.client'),
        ),
    ]
