# Generated by Django 4.0.5 on 2022-07-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_admin_bio_admin_fullname_admin_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='image',
            field=models.ImageField(blank=True, upload_to='interventions/'),
        ),
        migrations.AlterField(
            model_name='redflag',
            name='image',
            field=models.ImageField(blank=True, upload_to='flags/'),
        ),
    ]
